-- PRINTFLOWPRO - Reparo de persistencia da pagina Configuracoes
-- Execute este arquivo inteiro no Supabase SQL Editor.
-- Seguro e aditivo: nao apaga dados existentes.

alter table public.settings
  add column if not exists profit_margin numeric(5,2) default 40.00,
  add column if not exists top_bar_hours text,
  add column if not exists top_bar_show_pickup boolean default true,
  add column if not exists top_bar_phone text,
  add column if not exists footer_show_address boolean default true,
  add column if not exists footer_hours_message text,
  add column if not exists footer_hours_week text,
  add column if not exists footer_hours_sat text,
  add column if not exists footer_hours_sat_time text,
  add column if not exists footer_hours_sat_desc text,
  add column if not exists saas_enabled boolean default true,
  add column if not exists nfe_enabled boolean default false,
  add column if not exists ai_enabled boolean default false,
  add column if not exists company_address text,
  add column if not exists delivery_motoboy_price_km numeric(10,2) default 2.50,
  add column if not exists delivery_car_price_km numeric(10,2) default 4.50,
  add column if not exists delivery_min_fee numeric(10,2) default 10.00,
  add column if not exists catalog_header_message text,
  add column if not exists catalog_whatsapp text,
  add column if not exists free_pickup_alert boolean default true,
  add column if not exists catalog_footer_text text;

alter table public.companies
  add column if not exists logo_light text,
  add column if not exists logo_dark text,
  add column if not exists favicon text,
  add column if not exists instagram_url text,
  add column if not exists facebook_url text,
  add column if not exists youtube_url text,
  add column if not exists refund_policy text,
  add column if not exists show_payments_visa boolean default true,
  add column if not exists show_payments_mastercard boolean default true,
  add column if not exists show_payments_elo boolean default true,
  add column if not exists show_payments_hipercard boolean default true,
  add column if not exists show_payments_diners boolean default true,
  add column if not exists show_payments_amex boolean default true,
  add column if not exists show_payments_boleto boolean default true,
  add column if not exists show_payments_transferencia boolean default true,
  add column if not exists show_payments_pix boolean default true,
  add column if not exists show_delivery_sedex boolean default true,
  add column if not exists show_delivery_pac boolean default true,
  add column if not exists show_delivery_correios boolean default true,
  add column if not exists show_delivery_jadlog boolean default true,
  add column if not exists show_delivery_motoboy boolean default true,
  add column if not exists show_security_letsencrypt boolean default true,
  add column if not exists show_security_google boolean default true,
  add column if not exists card_benefits_1_title text default 'Ate 4x Sem Juros',
  add column if not exists card_benefits_1_subtitle text,
  add column if not exists card_benefits_1_active boolean default true,
  add column if not exists card_benefits_2_title text default 'Desconto no PIX',
  add column if not exists card_benefits_2_subtitle text,
  add column if not exists card_benefits_2_active boolean default true,
  add column if not exists card_benefits_3_title text default 'Frete para todo Brasil',
  add column if not exists card_benefits_3_subtitle text,
  add column if not exists card_benefits_3_active boolean default true,
  add column if not exists card_benefits_4_title text default 'Pontos de Coleta',
  add column if not exists card_benefits_4_subtitle text,
  add column if not exists card_benefits_4_active boolean default true,
  add column if not exists img_payments_visa text,
  add column if not exists img_payments_mastercard text,
  add column if not exists img_payments_elo text,
  add column if not exists img_payments_hipercard text,
  add column if not exists img_payments_diners text,
  add column if not exists img_payments_amex text,
  add column if not exists img_payments_boleto text,
  add column if not exists img_payments_transferencia text,
  add column if not exists img_payments_pix text,
  add column if not exists img_delivery_sedex text,
  add column if not exists img_delivery_pac text,
  add column if not exists img_delivery_correios text,
  add column if not exists img_delivery_jadlog text,
  add column if not exists img_delivery_motoboy text,
  add column if not exists img_security_letsencrypt text,
  add column if not exists img_security_google text;

update public.settings
set
  profit_margin = coalesce(profit_margin, 40.00),
  top_bar_show_pickup = coalesce(top_bar_show_pickup, true),
  footer_show_address = coalesce(footer_show_address, true),
  saas_enabled = coalesce(saas_enabled, true),
  nfe_enabled = coalesce(nfe_enabled, false),
  ai_enabled = coalesce(ai_enabled, false),
  delivery_motoboy_price_km = coalesce(delivery_motoboy_price_km, 2.50),
  delivery_car_price_km = coalesce(delivery_car_price_km, 4.50),
  delivery_min_fee = coalesce(delivery_min_fee, 10.00),
  free_pickup_alert = coalesce(free_pickup_alert, true);

select
  'printflow_settings_persistence_fix_ok' as status,
  count(*) as settings_total
from public.settings;
